### ISSUE TITLE
Crash while syncing with Unreal 4.23.2

### ISSUE THREAD

**Issue by Ecnassianer** [SRombauts/UE4PlasticPlugin#72] opened 2020-02-01 22:52 UTC
This weekend I've hit several crashes while syncing. Here's one of the stack traces:

LoginId:613d9eaa4e8ed3d6946337b95cc58f4a
EpicAccountId:ef9fa5175b244da18b9031b4e73c7eed

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x000000b8

UE4Editor_CoreUObject
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor_PlasticSourceControl
UE4Editor_PlasticSourceControl
UE4Editor_PlasticSourceControl
UE4Editor_PlasticSourceControl
UE4Editor_SourceControl
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll

Unrela 4.23.2, connecting to Plastic Cloud.

**Comment by SRombauts** [comment] 2020-02-03 09:03
Hi,

This is indeed à known issue of Unreal Engine itself, also affecting other source control Plugins. 

Here is the public issue that Epic opened to track the problem https://issues.unrealengine.com/issue/UE-63030
It has been marked as fixed in 4.24 though I haven't tried it myself yet. 

Cheers !

**Comment by SRombauts** [comment] 2020-02-03 09:06
Duplicate of #69

**Closed by SRombauts** 2020-02-03 09:06 UTC
Labels: unreal-bug
