### ISSUE TITLE
"New version of file exists in source control" status icon does not show when using multiple branches

### ISSUE THREAD

**Issue by davidcanadas** [SRombauts/UE4PlasticPlugin#80] opened 2020-07-28 13:38 UTC
The "New version of file exists in source control" status icon as described in https://docs.unrealengine.com/en-US/Engine/UI/SourceControl/index.html does not show in the Content Browser when using multiple branches.

Function `RunFileinfo` (`PlasticSourceControlUtils.cpp`) uses the following format pattern for the `fileinfo` command:
`"{RevisionChangeset};{RevisionHeadChangeset};{RepSpec};{LockedBy};{LockedWhere}"`

According to the Plastic SCM creators,` {RevisionHeadChangeset}` returns the head changeset in the same branch in which the workspace's in, but does not work across branches. Because of this, the "New version of file exists in source control" status icon does not show always.

*Example scenario*:

I have a file named `a.txt` with changes in chagesets 1, 3 and 5. My workspace is on changeset 4 (so using revision 3 for this object). Running the `fileinfo` command gives me wrong results for the head changeset I would expect:

`cm fileinfo a.txt --format="{RevisionChangeset};{RevisionHeadChangeset};{RepSpec};{LockedBy};{LockedWhere}"`
`3;3;localrepo@localhost;;`

while it shall be `3;5;localrepo@localhost;;` instead (as the actual head version shall be not the one in my branch, but the latest I've submitted).

**Comment by SRombauts** [comment] 2020-09-16 18:52
Sorry, I was so certain I had posted an answer on this 3rd of August... don't know how it ended it lost :(

So basically this is how Unreal Engine source control works.
By design, this part of the code is only checking the branch you are in: working on a release branch, you certainly don't want a "not at head" warning if a change as been submitted in the master branch that you branched of from

This is the same behavior in Perforce & Subversion.

There is however a relatively new obscure feature that I only started to use recently, that enables the source control provider to check for other specific sets of branches but for that you need
1. some code in one of your Editor code module
2. a new feature in this very plugin to support the above code. I have recently deal with such code so I could work on providing this

Regards
Sébastien

**Comment by dacanizares** [comment] 2021-03-22 17:43
Any news regarding this? Seems promising for my team's workflow.

**Comment by SRombauts** [comment] 2022-05-04 08:32
I have finally implemented this, it's merged on master and will be released in the coming weeks
https://github.com/PlasticSCM/UE4PlasticPlugin/pull/25 Detect files changed on another branch

**Closed by SRombauts** 2022-05-04 08:32 UTC
Labels: enhancement, question
