### ISSUE TITLE
Failed to enable Plastic SCM source control. You need to initialize the project as a Plastic SCM repository first.

### ISSUE THREAD

**Issue by Theotormon** [SRombauts/UE4PlasticPlugin#74] opened 2020-04-04 11:28 UTC
This is Unreal 4.24.3. Plastic SCM version 9.0.16.4140. Running on Mac OS 10.15.4.

I have an existing project that I sync'd to my laptop via Plastic SCM. I then opened the project in UE4 and attempted to connect to PSCM with your plugin.

After accepting (default) settings, I get an error that says:

"Failed to enable Plastic SCM source control. You need to initialize the project as a Plastic SCM repository first."

It then gives me a dialog to initialize a new workspace (not what I want to do, as the workspace already exists). If I do hit the button to "Create a new Plastic SCM workspace for the current project" I get another error:

"Error: Value cannot be null."
"Parameter name: path"

**Comment by SRombautsU** [comment] 2022-06-27 11:13
duplicate of https://github.com/SRombauts/UE4PlasticPlugin/issues/1 MacOS support

**Closed by SRombautsU** 2022-06-27 11:13 UTC
Labels: enhancement, macOS
