### ISSUE TITLE
Urgent help needed with broken ignore feature

### ISSUE THREAD

**Issue by lagauche** [SRombauts/UE4PlasticPlugin#76] opened 2020-04-19 05:42 UTC
If I place a file using the file explorer into the Content/Developers folder Plastic ignores it (it does not show up in Pending Changes), but if I add an asset to or move an asset into the Developers folder, in the UE4 Editor, that file gets added and shows up in the PlasticSCM Gui's pending changes.

This is wrecking our team at the moment. Any ideas?

**Comment by reveracorp** [comment] 2020-04-19 05:52
Oh wow, I just tested same and yes it does. Plastic GUI respects my ignore.conf ignore of Developers folder. But Plastic Plugin in UE4 checks it out in engine.

**Comment by lagauche** [comment] 2020-04-20 18:25
Hello just checking if you have any updates on this?

Incase it wasn't clear from my initial issue. The problem we're facing occurs when you ignore the /Content/Developers folder. If you move any assets inside the UE4 editor to that folder with Plastic Source Control on, it shows up in pending changes as added and wants to checking-in, but what we expect is that it would not show up in pending changes because that folder is set to ignore in the ignore.conf.

**Comment by SRombauts** [comment] 2020-04-23 07:28
Hello, yes it was clear from the beginning.
Sorry for not answering before, I am quite overloaded with work & kids here at home!

Basically, Unreal Editor doesn't deal with Ignore files, so it does "Add" every files that you put into an ignored directory.
If you use Plastic SCM GUI to go into an ignored directory, you can still add files to source control explicitly. There is not "safety feature" to prevent you.

So right now I don't really know what to do with this; I could try to improve Unreal Editor to deal with ignored folders (probably complex & won't be integrated), or the plugin to filter out those call to not execute the "Add" on those files (seems also very risky).

Let me ask Codice Software if they can implement such a safety measure in plastic SCM itself.

Cheers!
Sébastien

**Comment by lagauche** [comment] 2020-04-24 00:42
Thanks yes! No worries : ) Do you have any ideas for a temporary solution? Maybe some sequence of button presses once I go back to the Plastic GUI and see all the files in an ignored folder show up as pending changes?

I wouldn't want to delete those of course and I doubt (but don't know) if undo would do anything desirable.

The goal here is simply that our team needs that dev folder to test assets we don't want to checkin so if there is any way to prevent my team from checking in those assets in the dev folder.

**Comment by ftrx** [comment] 2020-04-29 09:26
Just  a personal input:
I think it is usually good practice to include all content files and folders, even developer folders, into source control.

1. Missing content can break your project or at least makes it annoying to fix, especially when your not an engine pro.
2. Sure developers content should not be used in production assets but it happens, especially when you move assets from a developer folder into production. which can lead to point 1.
3. For me personally its nice to have my own dev stuff version controlled.

The more version control the better ;)

Anyways its a bit a weird behavior, but i think its by design that everything gets added.

**Comment by lagauche** [comment] 2020-04-29 15:53
> Just a personal input:
> I think it is usually good practice to include all content files and folders, even developer folders, into source control.
> 
> 1. Missing content can break your project or at least makes it annoying to fix, especially when your not an engine pro.
> 2. Sure developers content should not be used in production assets but it happens, especially when you move assets from a developer folder into production. which can lead to point 1.
> 3. For me personally its nice to have my own dev stuff version controlled.
> 
> The more version control the better ;)
> 
> Anyways its a bit a weird behavior, but i think its by design that everything gets added.

I understand everything you're saying about your preferred workflow but saying that an ignored asset or folder should not be ignored doesn't address the issue.

ignore.conf is up to us to configure and I appreciate your preferences, but it either works or it doesn't and right now it doesn't.

**Comment by SRombauts** [comment] 2020-09-16 19:10
I think that @ftrx comments is in fact very appropriate: Unreal & Epic Games are sometimes quite opinionated with the workflow they support.

In my experience, trying to work against the tools in hand is not really paying off.

I'll close this as a unreal-bug as I won't be able to tackle Engine changes without Epic support.

Regards,
Sébastien

**Closed by SRombauts** 2020-09-16 19:10 UTC
Labels: bug

**Comment by SRombauts** [comment] 2022-05-04 10:44
This has finally been fixed (or worked around) in the plugin and tracked by https://github.com/SRombauts/UE4PlasticPlugin/issues/85
